- config/services.yaml
@rebuy-de/prp-cloud-infrastructure
> update of github paths

- README.md
- settings/project_config.go
- settings/project_config_test.go
> Readme adjustment

- config/services.yaml
- git/git_test.go
- git/sparse_checkout_test.go
- git/testutils_test.go
- main.go
- settings/project_config_test.go
- settings/setting.go
- templates/parse_manifests.go
- util/test.go
* fix my-web
* add heapster
* fix gofmt
I could split this PR.
> fix my-web and add heapster

- config/services.yaml
> fix green-web location

- config/services_test2.yaml
- settings/project_config_test.go
> tests shouldn't use production data

- app.go
- git/git.go
- glide.lock
- glide.yaml
- kubernetes/kubernetes.go
- logger.go
- retry.go
- util/util.go
Change logger in preparation of parallelizing the git fetch. (ie we don't want to see a text wall when deploying, but we still may want to investigate errors via a text file) 
Also: much color, such wow
> Change logger

- app.go
- main.go
Add target flag, so we are able to deploy a single service.
> add target flag

- settings/service.go
- settings/service_test.go
> make compatible with git 1.7

- cmd/command_root.go
> Correct typo

- cmd/app_test.go
- pkg/git/git.go
> Pull from master..

- Dockerfile
- cmd/goal_fetch.go
- golang.mk
- pkg/settings/builder_test.go
- pkg/settings/test-fixtures/services_test.yaml
* add lower case alias for `gitCommitID` (`git-commit-id`)
* update build files (https://github.com/rebuy-de/golang-template/pull/3)
> add lower case git-commit-id

- cmd/goal_fetch.go
> fix commit id

- pkg/templates/parse_manifests.go
So something like `blue-web-{{.gitBranchName | ToLower}}` is possible.
> add ToLower to templates

- cmd/util_test.go
- pkg/api/generate.go
> fix branch deployment

- cmd/dump_config.go
- cmd/dump_settings.go
- cmd/generate.go
- cmd/parameters.go
- cmd/root.go
- cmd/util.go
- glide.lock
- glide.yaml
- pkg/api/generate.go
- pkg/api/generate_test.go
- pkg/api/parameters.go
- pkg/gh/client.go
- pkg/kubectl/kubectl.go
- pkg/settings/settings.go
Also had to rename the logrus package, because the Graylog hook uses a lower case one :-(
> add GELF support

- cmd/parameters.go
- glide.lock
- glide.yaml
- pkg/api/app.go
- pkg/api/apply.go
- pkg/api/generate.go
- pkg/api/generate_test.go
- pkg/api/parameters.go
- pkg/gh/client.go
- pkg/statsdw/interface.go
- pkg/statsdw/null.go
- pkg/statsdw/wrapper.go
> add statsd support

- cmd/apply.go
- cmd/generate.go
- cmd/root.go
- pkg/api/apply.go
- pkg/api/generate.go
* Improved logging, so it only prints useful data as info.
* Added `--json-logs` flag, so the log output will be printed as JSON.
**Example**
```
{
"Commit": "4acb74452a817953f24cf17467138262ee986909",
"Date": "Thu Jun 22 14:26:37 CEST 2017",
"Level": "debug",
"Message": "kubernetes-deployment started",
"Time": "2017-06-22T14:29:23+02:00",
"Version": "v5.0.0.alpha.5.dirty"
}
{
"Filename": "github.com/rebuy-de/cloud/deployments.yaml",
"GitHubToken": "b1e2****",
"Kubeconfig": "/home/sven/.kube/config-production",
"Level": "debug",
"Message": "config loaded",
"Time": "2017-06-22T14:29:23+02:00"
}
{
"Level": "debug",
"Message": "downloading file from GitHub",
"Owner": "rebuy-de",
"Path": "deployments.yaml",
"Ref": "master",
"Repo": "cloud",
"Time": "2017-06-22T14:29:23+02:00"
}
{
"FromCache": …
```
> improve logging

- pkg/statsdw/wrapper.go
> remove debug fmt.Printf

- pkg/api/apply.go
- pkg/gh/client.go
- pkg/interceptors/waiter/deployment.go
> https://jira.rebuy.de/browse/CLOUD-1163
* fix waitgroup `done()`
* add more log data
* refetch deployment after apply, since hubot behaved differently than my machine
* fix wait for multiple deployments
* fix fetching of GitHub directories for branches
> CLOUD-1163 fix waiter

- pkg/interceptors/waiter/deployment.go
- pkg/kubeutil/pods.go
> https://jira.rebuy.de/browse/CLOUD-1163
This mutes ErrImagePull message for 30 seconds, so it is less annoying.
> CLOUD-1163 mute ErrImagePull for 30s

- pkg/interceptors/waiter/deployment.go
It didn't work, because I checked for the wrong error message.
> fix warn mute

- pkg/api/render.go
Ignoring empty files to support this: https://github.com/rebuy-de/web/pull/191
> ignore empty files

- pkg/interceptors/waiter/deployment.go
We don't need to get notified for each Kubernetes deployment separately.
> mute ErrImagePull globally

- pkg/api/app.go
- pkg/api/apply.go
- pkg/api/generate_test.go
- pkg/api/render.go
- pkg/interceptors/interfaces.go
- pkg/interceptors/multi.go
- pkg/interceptors/rmresspec/interceptor.go
- pkg/interceptors/rmresspec/interceptors_test.go
- pkg/settings/settings.go
- pkg/settings/test-fixtures/services-clean-golden.json
- pkg/settings/test-fixtures/services-context-golden.json
- pkg/settings/test-fixtures/services-plain-golden.json
- pkg/settings/test-fixtures/services.yaml
> https://jira.rebuy.de/browse/CLOUD-1187
> CLOUD-1187 remove resource spec

- pkg/api/app.go
- pkg/api/fetch.go
- pkg/api/generate_test.go
- pkg/interceptors/prestopsleep/interceptor.go
- pkg/interceptors/prestopsleep/interceptors_test.go
- pkg/settings/default.go
- pkg/settings/interceptors.go
- pkg/settings/service.go
- pkg/settings/test-fixtures/services-clean-golden.yaml
- pkg/settings/test-fixtures/services-context-golden.yaml
- pkg/settings/test-fixtures/services-plain-golden.yaml
- pkg/settings/test-fixtures/services.yaml
The last part of the config refactoring. This are the actual changes, which make https://github.com/rebuy-de/cloud-infrastructure/pull/304 work.
> improve interceptor config

- cmd/dump_settings.go
- pkg/api/fetch.go
- pkg/api/generate_test.go
- pkg/api/test-fixtures/deployments-golden.yaml
- pkg/settings/service.go
- pkg/settings/settings.go
With this we don't need add entries to the config, if they only contain `repo`.
> Guess services

- cmd/util.go
- main.go
- pkg/api/app.go
- pkg/api/apply.go
- pkg/api/fetch.go
- pkg/api/test-fixtures/deployments-golden.yaml
- pkg/cmdutil/exit.go
- pkg/gh/client.go
- pkg/gh/fake/impl.go
- pkg/interceptors/interfaces.go
- pkg/interceptors/multi.go
- pkg/interceptors/statuschecker/interceptor.go
- pkg/interceptors/statuschecker/interceptors_test.go
- pkg/settings/default.go
- pkg/settings/interceptors.go
- pkg/settings/test-fixtures/services-clean-golden.yaml
- pkg/settings/test-fixtures/services-context-golden.yaml
- pkg/settings/test-fixtures/services-plain-golden.yaml
*SCNR*
This makes `kubernetes-deployment` wait for certain build statuses, which are stored at GitHub and generated from Jenkins.
> Add GitHub status watcher

- pkg/api/app.go
- pkg/api/test-fixtures/deployments-golden.yaml
- pkg/interceptors/prestopsleep/options.go
- pkg/interceptors/statuschecker/interceptor.go
- pkg/interceptors/statuschecker/interceptors_test.go
- pkg/interceptors/statuschecker/options.go
- pkg/settings/default.go
- pkg/settings/interceptors.go
- pkg/settings/test-fixtures/services-clean-golden.yaml
- pkg/settings/test-fixtures/services-context-golden.yaml
- pkg/settings/test-fixtures/services-plain-golden.yaml
- pkg/settings/tristate.go
* moves options into the actual packages
* makes the durations configurable
* rename jobRegex to contextRegex
> Improve statuschecker options

- pkg/interceptors/waiter/interceptor.go
- pkg/interceptors/waiter/interceptors_test.go
I guess that's the downside of golangs interface system.
> fix waiter

- pkg/interceptors/rmresspec/interceptor.go
@rebuy-de/it-platform 
fix removal of resource spec for init containers
> fix init container remove resources

- pkg/templates/functions.go
- pkg/templates/render.go
Required, so we can do magic like this: https://github.com/rebuy-de/feed-generator/pull/153
> add makeSlice template function

- pkg/api/render.go
- pkg/templates/render.go
- pkg/templates/render_test.go
> fix MakeSlice

- pkg/api/app.go
- pkg/api/apply.go
- pkg/api/test-fixtures/deployments-golden.yaml
- pkg/interceptors/interfaces.go
- pkg/interceptors/multi.go
- pkg/interceptors/rmoldjob/interceptor.go
- pkg/interceptors/rmoldjob/interceptors_test.go
- pkg/interceptors/waiter/interceptor.go
- pkg/interceptors/waiter/interceptors_test.go
- pkg/settings/interceptors.go
- pkg/settings/test-fixtures/services-clean-golden.yaml
- pkg/settings/test-fixtures/services-context-golden.yaml
- pkg/settings/test-fixtures/services-plain-golden.yaml
Just hacked together. Still needs a test.
Do we want this?
> add removeOldJob interceptor

- README.md
> add development status

- pkg/api/generate_test.go
- pkg/api/test-fixtures/deployments-golden.yaml
- pkg/api/test-fixtures/deployments.yaml
- pkg/settings/default.go
- pkg/settings/service.go
- pkg/settings/settings.go
- pkg/settings/test-fixtures/services-clean-golden.yaml
- pkg/settings/test-fixtures/services-context-golden.yaml
- pkg/settings/test-fixtures/services-plain-golden.yaml
- pkg/settings/test-fixtures/services.yaml
> add aliases

- pkg/interceptors/multi.go
@rebuy-de/prp-kubernetes-deployment please review
> No close on nil

- pkg/interceptors/rmresspec/interceptor.go
> Fix small typo

- pkg/api/app.go
- pkg/api/test-fixtures/deployments-golden.yaml
- pkg/interceptors/annotater/interceptor.go
- pkg/interceptors/annotater/interceptors_test.go
- pkg/interceptors/annotater/test-fixtures/deployment-golden.json
- pkg/settings/interceptors.go
- pkg/settings/test-fixtures/services-clean-golden.yaml
- pkg/settings/test-fixtures/services-context-golden.yaml
- pkg/settings/test-fixtures/services-plain-golden.yaml
Adds annotations to deployed objects.
> add annotations

- pkg/interceptors/rmoldjob/interceptor.go
This adds an annotation `rebuy.com/cascade-delete` to jobs, with allows an cascading deletion (ie deletes all pods too).
/cc @omares
> cascade on job deletion

- pkg/gh/client.go
We get an error, if a directory contains a subdirectory.
```
ERRO[0001] failed to fetch project: unable to decode file 'github.com/rebuy-de/my-repo/deployment/k8s/@9505f3153a841bffbcd306857b49a6fb0e23a804': unable to fetch file 'github.com/rebuy-de/my-repo/deployment/k8s/backup@9505f3153a841bffbcd306857b49a6fb0e23a804' from GitHub; probably it's a directory 
```
This changes the behaviour so it ignores subdirectories.
> fix fetching directory from GitHub

- golang.mk
@rebuy-de/prp-kubernetes-deployment please review
> adds vendor dependency to build target

- pkg/interceptors/annotater/interceptor.go
- pkg/interceptors/annotater/interceptors_test.go
- pkg/interceptors/annotater/test-fixtures/pvc-golden.json
It looks like the accessor is overwriting the existing values instead of adding to them.
> fix annotator

- pkg/gh/client.go
> Use a different field to get the author name

- Gopkg.lock
Updating to go `1.10.3` and rerunning `dep ensure` fixed the issue.
> Fix travis dirty builds

- pkg/gh/client.go
Missed this one in the earlier PR...
> Another buggy author name call

- Gopkg.lock
- Gopkg.toml
- pkg/interceptors/prestopsleep/interceptor.go
- pkg/interceptors/prestopsleep/interceptors_test.go
- pkg/interceptors/prestopsleep/test-fixtures/deployment-golden.json
- pkg/interceptors/rmresspec/interceptor.go
> Update Kubernetes client

- Gopkg.lock
- Gopkg.toml
- pkg/api/render.go
- pkg/api/render_test.go
- pkg/gh/client.go
- pkg/gh/fake/impl.go
- pkg/gh/fake/package_test.go
- pkg/gh/fake/utils.go
- pkg/gh/file.go
- pkg/gh/importer.go
- pkg/gh/importer_test.go
- pkg/gh/location.go
- pkg/settings/settings.go
Creates an Jsonnet importer, that can access GitHub files.
Tested with https://github.com/rebuy-de/web/pull/2313 on staging.
Please take a look at the test cases in `pkg/gh/importer_test.go`, if these make sense to you. Especially if the selected branch would be the one you expect.
> add Jsonnet importer

- Dockerfile
After merging https://github.com/rebuy-de/rebuy-hubot/pull/126, I though it makes sense to bundle `kubectl` also into the Docker image.
> bundle kubectl with Docker image

- pkg/api/app.go
- pkg/interceptors/injector/interceptor.go
- pkg/interceptors/injector/options.go
- pkg/settings/interceptors.go
> https://jira.rebuy.de/browse/CLOUD-1740
> CLOUD-1740 make linkerd version configurable

- Dockerfile
- pkg/api/test-fixtures/deployments-golden.yaml
- pkg/interceptors/injector/interceptor_test.go
- pkg/interceptors/injector/test-fixtures/deployment-golden.json
- pkg/settings/test-fixtures/services-clean-golden.yaml
- pkg/settings/test-fixtures/services-context-golden.yaml
- pkg/settings/test-fixtures/services-plain-golden.yaml
> Add test target to makefile

- Dockerfile
> Update kubectl to 1.13.2

- .github/main.workflow
- Dockerfile
- LICENSE
- golang.mk
> Follow up to https://github.com/rebuy-de/golang-template/pull/23
> use verify action from golang-templates

- cmd/kubernetes-deployment/root.go
> Make kubeconfig optional

- pkg/api/render.go
by removing all lines with comments only before moving on
> Fix manifest comments breaking parser

- pkg/api/app.go
- pkg/api/test-fixtures/deployments-golden.yaml
- pkg/interceptors/injector/interceptor.go
- pkg/interceptors/injector/options.go
- pkg/settings/interceptors.go
- pkg/settings/test-fixtures/services-clean-golden.yaml
- pkg/settings/test-fixtures/services-plain-golden.yaml
It's not used so lets get rid of it
> Remove linkerd version

- .github/main.workflow
ptal @rebuy-de/prp-kubernetes-deployment
> Update github actions in golang template

- pkg/api/app.go
- pkg/api/test-fixtures/deployments-golden.yaml
- pkg/interceptors/grafannotator/interceptor.go
- pkg/settings/interceptors.go
- pkg/settings/test-fixtures/services-clean-golden.yaml
- pkg/settings/test-fixtures/services-plain-golden.yaml
> CLOUD-1927 Add Interceptor to send annotations to Grafana

- pkg/api/app.go
- pkg/api/test-fixtures/deployments-golden.yaml
- pkg/interceptors/injector/interceptor.go
- pkg/interceptors/injector/interceptor_test.go
- pkg/interceptors/injector/options.go
- pkg/interceptors/injector/test-fixtures/deployment-golden.json
- pkg/interceptors/prestopsleep/interceptors_test.go
- pkg/settings/default.go
- pkg/settings/interceptors.go
- pkg/settings/test-fixtures/services-clean-golden.yaml
- pkg/settings/test-fixtures/services-plain-golden.yaml
* Add a way to easily change the linkerd-proxy sidecar
* Add a general test for linkerd injection
> Change linkerd proxy configuration to set outbound connect timeout

- pkg/interceptors/imagechecker/interceptor.go
Things I am unsure about:
- Will hubot display the output correctly if I just `println` the message? Or do I have to print to `stderr` for it to work? (see [here](https://github.com/rebuy-de/rebuy-hubot/blob/master/hubert/scripts/kubernetes.coffee#L45-L56))
- The ticket said `repeat every minute`, but the check interval is configurable. Is the "every 4 tries" approach still okay?
> CLOUD-1979 Improve logging in image check

- pkg/interceptors/waiter/interceptor.go
- pkg/interceptors/waiter/util.go
- pkg/interceptors/waiter/util_test.go
> https://jira.rebuy.de/browse/CLOUD-2001
> CLOUD-2001 fix deployment waiter
