app.go
app_test.go
config/services.yaml
git/git.go
settings/service.go
settings/service_test.go

* somebody doesn't use gofmt style
* updated `config/services.yaml` to our current repo structure
* set default path to `/deployment/k8s` to match our real default

fix config

---

app.go
app_test.go
command-deploy.go
command-fetch.go
command-render.go
commands.go
commands_test.go
main.go
settings/setting.go

Use commands instead of `-skip-*` flags.
Now we can do:
* `kubernetes-deployment fetch`
* `kubernetes-deployment render`
* `kubernetes-deployment deploy`
* `kubernetes-deployment all`
Also I splitted the commands into different files, so the PR looks bigger than it actually is.

Add commands

---

app.go
command-fetch.go
command-render.go

This makes kubernetes-deployment not remove the output directory on each start, so we are able to use other commands than `all`.

fix commands

---

settings/service.go
settings/service_test.go

Fix to not overwrite service name. That means with 
```yaml
services:
- name: rabbitmq
repo: github.com/rebuy-de/k8s-rabbitmq
path: manifests
```
I want to do `kubernetes-deployment -t rabbitmq all` and not `kubernetes-deployment -t k8s-rabbitmq-manifests all`.

don't overwrite service name

---

.gitignore
cmd/goal_fetch.go
cmd/goal_render.go
cmd/test-fixtures/services_test.yaml
pkg/settings/builder.go
pkg/settings/builder_test.go
pkg/settings/service.go
pkg/settings/setting.go
pkg/settings/test-fixtures/services_test.yaml

Fix case, because `cluster-domain` isn't allowed by Golang templates.

Fix key case

---

pkg/git/git.go

@rebuy-de/prp-kubernetes-deployment Use fetch, not pull, to allow test of newly created kubernetes manifests using branch deployment.
**Please review!**

Use fetch instead of pull

---

pkg/templates/render.go

We need to use the `text` package instead of the `html` package to rendering templates. Otherwise it tries to escape the templates, which converts stuff like `<` into `&lt;`.

fix template rendering

---

cmd/root.go

We want to filter messages by `facility` like in our other services.

add facility for Graylog labels

---

README.md
pkg/templates/functions.go
pkg/templates/functions_test.go
pkg/templates/render.go

Adds a template function, so random strings can safely used for `meta.name`.

add identifier template function

---

main.go

Apparently golang always initializes seed with `1`.

initialize seed

---

cmd/apply.go
cmd/dump_config.go
cmd/dump_settings.go
cmd/generate.go
cmd/util.go
main.go
pkg/api/app.go
pkg/api/apply.go
pkg/api/fetch.go
pkg/api/generate.go
pkg/api/generate_test.go
pkg/api/render.go
pkg/gh/client.go
pkg/gh/fake/package_test.go
pkg/settings/settings.go

I did some refactoring:
* I divided the `Generate` function into multiple part, because it got a bit long. Also we need to add additional functionality to this function later, which would make it even bigger.
* I refactored the error handling a bit. Now there is an additional debug log entry with the [stack trace](https://github.com/pkg/errors). Also I had to create a wrapper function with does a panic on errors, because `os.Exit()` [doesn't honor deferrers](https://stackoverflow.com/questions/27629380/how-to-exit-a-go-program-honoring-deferred-calls).

refactor api package

---

pkg/api/app.go
pkg/statsdw/wrapper.go

Fixes failed builds because of `failed to initialize statsd client: dial udp: i/o timeout` errors. Now, kubernetes deployment just warns an continues.

continue on statsd errors

---

pkg/api/app.go
pkg/interceptors/prestopsleep/interceptor.go
pkg/interceptors/prestopsleep/interceptors_test.go
pkg/interceptors/prestopsleep/test-fixtures/deployment-golden.json

Adds a preStop sleep for all containers which don't already have preStop hook. I hardcoded one second. This should be enough and I am too lazy do make it configurable right now.

add preStop sleep

---

pkg/gh/location.go
pkg/settings/service.go
pkg/settings/test-fixtures/services-clean-golden.yaml
pkg/settings/test-fixtures/services-context-golden.yaml
pkg/settings/test-fixtures/services-plain-golden.yaml

Use `omitempty` for all YAML fields, so the golden files are less cluttered.

make golden files more clean

---

pkg/api/app.go
pkg/gh/location.go
pkg/settings/default.go
pkg/settings/service.go
pkg/settings/settings.go
pkg/settings/test-fixtures/services-clean-golden.yaml
pkg/settings/test-fixtures/services-context-golden.yaml
pkg/settings/test-fixtures/services-plain-golden.yaml
pkg/templates/variables.go

This refactored `Settings` in `pkg/settings`, so it uses `Service` everywhere instead of `Defaults` and `Context`. This makes the code cleaner.
The downside is, that someone could define eg `name` in a context or `context` in a service, which doesn't make much sense.

Generalize pkg/settings

---

pkg/api/apply.go
pkg/api/render.go
pkg/interceptors/interfaces.go
pkg/interceptors/multi.go
pkg/interceptors/prestopsleep/interceptor.go
pkg/interceptors/prestopsleep/interceptors_test.go
pkg/interceptors/rmresspec/interceptor.go
pkg/interceptors/rmresspec/interceptors_test.go

This gives the Interceptor interface a better and more structured naming (see `pkg/interceptors/interfaces.go`). Also it renames the interfaces like recommended in Golang conventions.

refactor interceptor interface

---

pkg/api/app.go
pkg/api/fetch.go

This makes the interceptors configurable on service level instead of context level. This can for example be used to set `ghStatusChecker` context name to a specific value.

move interceptor config to service level

---

pkg/interceptors/waiter/interceptor.go

It looks like the pod restart warnings aren't working correctly sometimes. We need more log data to verify that.

add manifest to pod failure logs

---

pkg/kubeutil/pods.go

> https://jira.rebuy.de/browse/CLOUD-1266
This fixes the restart warnings in HipChat by ignoring Pods, which are in pending deletion.

CLOUD-1266 fix annoying pod restart notifications

---

cmd/root.go

in root.go there was a check for the existance of github
demplyments.yaml file path, but not for github token or kubeconfig path,
resulting in an unhandled crash if any of the two were absent
this was addressed by putting extra checks and error messages in the
root.go file
@rebuy-de/prp-kubernetes-deployment  please review

adds checks for gh token and kubeconfig file path

---

glide.lock
glide.yaml
pkg/interceptors/prestopsleep/test-fixtures/deployment-golden.json

@rebuy-de/prp-kubernetes-deployment - PTAL
Bumped the client version to 4.0 which is for k8s 1.7.
Tested deploying:
- PodDisruptionBudget
- Deployment
- CronJob
- Job
- StatefulSet
- Implicit PersistentVolumeClaim as part of StatefulSet
- Service
- Ingress
- ReplicaSet
- DaemonSet

Bump k8s client

---

pkg/api/fetch.go
pkg/settings/services.go
pkg/settings/settings.go
pkg/settings/settings_test.go
pkg/settings/test-fixtures/services-clean-golden.yaml
pkg/settings/test-fixtures/services-context-golden.yaml
pkg/settings/test-fixtures/services-plain-golden.yaml
pkg/settings/test-fixtures/services.yaml

This adds support for subdirectories when guessing the project settings (ie projects that do not have an entry in the `cloud-infrastructure/deployments.yaml` file). This means we could do something like `hubert deploy k8s-elasicsearch/jaeger` and `hubert deploy k8s-elasicsearch/graylog`, which would deploy the files in `github/.../k8s-elasticsearch/deployment/k8s/jaeger/` and `github/.../k8s-elasticsearch/deployment/k8s/graylog`.
Still needs testing.
@rebuy-de/prp-kubernetes-deployment What do you think?

add support for subdirectories

---

Gopkg.lock
Gopkg.toml
pkg/interceptors/annotater/interceptor.go
pkg/interceptors/annotater/interceptors_test.go
pkg/interceptors/annotater/test-fixtures/service-golden.json
pkg/interceptors/annotater/test-fixtures/statefulset-golden.json

This annotates every object and not just Daemonsets and Statefulsets. IMO this is the only way to identify stale Kubernetes objects (like old PVCs with 750GiB).

annotate every object

---

pkg/interceptors/annotater/interceptor.go
pkg/interceptors/annotater/interceptors_test.go
pkg/interceptors/annotater/test-fixtures/deployment-golden.json
pkg/interceptors/annotater/test-fixtures/pvc-golden.json
pkg/interceptors/annotater/test-fixtures/service-golden.json
pkg/interceptors/annotater/test-fixtures/statefulset-golden.json

`Time.String()` produces a weird debug format that looks like this: `2018-05-31 13:45:04.231590273 +0200 CEST m=+1.509596926`.
Also I had to fiddle around with the time zones because:
1. `deployment-date` and `commit-date` should have the same TZ.
2. Tests should use UTC, because otherwise the golden file would depend on the local time zone.

fix date formatting

---

golang.mk

Travis wants to update the lock file again. Fortunately `dep` has a flag to avoid this.

fix vendoring

---

pkg/api/generate_test.go
pkg/api/render.go
pkg/kubectl/kubectl.go
pkg/kubeutil/util.go

kubernetes-deployment also parses the output of `kubectl apply`, therefore we need to use a proper decoder there too.

fix apply for unknown objects

---

pkg/interceptors/annotater/interceptor.go
pkg/interceptors/annotater/interceptors_test.go
pkg/interceptors/annotater/test-fixtures/deployment-golden.json
pkg/interceptors/annotater/test-fixtures/deployment-name-golden.json
pkg/interceptors/annotater/test-fixtures/pvc-golden.json
pkg/interceptors/annotater/test-fixtures/statefulset-golden.json

This automatically adds a name label to any manifest, which matches the actual manifest name. This gives use better filtering possibilities in Grafana. Especially in the `Workloads`, it would be a bit easier to filter stuff.
Also:
* it does not overwrite existing labels
* it warns if the names do not match, to enforce some consistency

add name label

---

pkg/interceptors/injector/interceptor.go
pkg/interceptors/injector/test-fixtures/deployment-golden.json

> https://jira.rebuy.de/browse/CLOUD-1740
Values come from [Prometheus](https://prometheus.production.rebuy.cloud/graph?g0.range_input=1h&g0.expr=node_pod_container%3Acontainer_cpu_usage_seconds%3Arate1m%7Bcontainer%3D%22linkerd-proxy%22%7D&g0.tab=0&g1.range_input=1h&g1.expr=node_pod_container%3Acontainer_memory_usage_bytes%3Asum%7Bcontainer%3D%22linkerd-proxy%22%7D&g1.tab=0).
*Edit:* These are only requests :-/

CLOUD-1740 limit linkerd proxy requests

---

Dockerfile
go.mod
go.sum
pkg/api/app.go
pkg/interceptors/injector/test-fixtures/deployment-golden.json
pkg/settings/settings.go
pkg/settings/settings_test.go

This allows reading the settings from a ConfigMap. It has the advantage, that a client just needs to configure their kubeconfig and does not have to provide a context. This also makes it possible to remove the context from the settings (#129), without having to wait for the kubernetes-deployment-server branch.
Sorry for all these unfocused PRs, but I want to make sure I do not provide a PR with 5k changes at the end.

read settings from configmap

---

go.mod
go.sum
pkg/api/render.go
pkg/api/render_test.go
pkg/api/test-fixtures/render-golden-resolve-git-sha-jsonnet.json
pkg/api/test-fixtures/render-resolve-git-sha.jsonnet
pkg/gh/location.go

Adds a native function, that resolves a git SHA from another repository. This can be useful when splitting Dockerfile and deployment manifests.
It works only with Jsonnet and looks like `std.native("resolveGitSHA")("github.com/rebuy-de/test@master")`, which resolves into a string containing the SHA. See changed files in `pkg/api/test-fixtures/` for an full example.

resolve git sha

---

pkg/interceptors/annotater/interceptor.go
pkg/interceptors/annotater/test-fixtures/cronjob-golden.json
pkg/interceptors/annotater/test-fixtures/daemonset-golden.json
pkg/interceptors/annotater/test-fixtures/deployment-golden.json
pkg/interceptors/annotater/test-fixtures/job-golden.json
pkg/interceptors/annotater/test-fixtures/statefulset-golden.json

Remove the deployment date from pod templates, because it causes a new rollout on every deployment, which we do not want.

remove deployment date from pod templates

---

cmd/k26r/app.go
cmd/kubernetes-deployment/parameters.go
cmd/kubernetes-deployment/root.go
pkg/api/app.go
pkg/api/generate_test.go
pkg/api/parameters.go
pkg/settings/settings.go
pkg/settings/settings_test.go

There is no need for reading settings from file anymore. Also it reduces the lines of code, which is nice.
Now it always reads the settings from the ConfigMap `default/kubernetes-deployment`.

hardcode settings source

---

pkg/interceptors/annotater/interceptor.go

In case of the VPA the label `workload-name` contained a colon, which caused some trouble.
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

CLOUD-1928 Replace colons in labels since they are forbidden

---

pkg/gh/client.go
pkg/gh/file.go

Linkerd is still making trouble on some staging deployments, because the namespace is missing. This should fix it.

sort files from GitHub

---

pkg/interceptors/annotater/interceptor.go
pkg/interceptors/injector/interceptor.go
pkg/interceptors/prestopsleep/interceptor.go
pkg/interceptors/rmresspec/interceptor.go
pkg/kubeutil/accessor.go
pkg/kubeutil/accessor_test.go
pkg/kubeutil/pods.go

We are using those type switches often and I need it again for https://jira.rebuy.de/browse/CLOUD-1942. Also we would need to search and replace on multiple places, if there is a new API version of something. Therefore putting it into a common function.

Refactor: Add accessors
